### ISSUE TITLE
bro why this file is not work https://github.com/Shreeshrii/tesstrain-ckb (Kurdish)

### ISSUE THREAD

**Issue by abasakre** [Shreeshrii/tessdata_arabic#2]
bro why this file is not work:
https://github.com/Shreeshrii/tesstrain-ckb (Kurdish)

**Comment by Shreeshrii** [comment]
Tesseract training in Arabic script has some problems related to numbers and punctuation. Not sure how good the finetuned traineddata files are. You are welcome to try and provide feedback. Files should be accessible.
